language: node_js
node_js:
- node
- '6'
- '4'
addons:
  code_climate:
    repo_token: 6f6d99b797e1e89da5e284976db3b8acb6b7ddc6732d61936ac75414c003c934
notifications:
  email: false
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
